name: flutter_steps
description: A customizable widget that allows you to display a series of steps in a horizontal or vertical direction.
version: 1.0.3
repository: https://github.com/elrizwiraswara/flutter_steps

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:

topics:
  - steps
  - flutter-steps
  - steps-widget
  - stepper
  - flutter-stepper